"use client"

import { useState, useMemo, useCallback } from "react"
import { Sparkles, Plus, CheckSquare, Filter, RefreshCw, ClipboardList } from "lucide-react"
import { cn } from "@/lib/utils"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue,
} from "@/components/ui/select"
import {
    Dialog,
    DialogContent,
    DialogHeader,
    DialogTitle,
    DialogFooter,
} from "@/components/ui/dialog"
import { TaskCard, Task } from "./TaskCard"

interface TasksClientProps {
    initialTasks: Task[]
}

const PRIORITY_ORDER: Record<string, number> = { URGENT: 0, HIGH: 1, MEDIUM: 2, LOW: 3 }

export default function TasksClient({ initialTasks }: TasksClientProps) {
    const [tasks, setTasks] = useState<Task[]>(initialTasks)
    const [generating, setGenerating] = useState(false)
    const [filterStatus, setFilterStatus] = useState("ACTIVE")
    const [filterPriority, setFilterPriority] = useState("ALL")
    const [filterCategory, setFilterCategory] = useState("ALL")
    const [search, setSearch] = useState("")
    const [showAddDialog, setShowAddDialog] = useState(false)
    const [newTask, setNewTask] = useState({ title: "", description: "", priority: "MEDIUM", category: "" })
    const [addLoading, setAddLoading] = useState(false)
    const [generateMessage, setGenerateMessage] = useState("")

    // Filtered + sorted tasks
    const filteredTasks = useMemo(() => {
        return tasks
            .filter(t => {
                if (filterStatus === "ACTIVE") return t.status === "PENDING" || t.status === "IN_PROGRESS"
                if (filterStatus === "DONE") return t.status === "DONE"
                if (filterStatus === "DISMISSED") return t.status === "DISMISSED"
                return true
            })
            .filter(t => filterPriority === "ALL" || t.priority === filterPriority)
            .filter(t => filterCategory === "ALL" || t.category === filterCategory)
            .filter(t => !search || t.title.toLowerCase().includes(search.toLowerCase()) ||
                t.description?.toLowerCase().includes(search.toLowerCase()) ||
                t.application?.company.toLowerCase().includes(search.toLowerCase()))
            .sort((a, b) => {
                const pa = PRIORITY_ORDER[a.priority] ?? 2
                const pb = PRIORITY_ORDER[b.priority] ?? 2
                if (pa !== pb) return pa - pb
                if (a.dueDate && b.dueDate) return new Date(a.dueDate).getTime() - new Date(b.dueDate).getTime()
                if (a.dueDate) return -1
                if (b.dueDate) return 1
                return 0
            })
    }, [tasks, filterStatus, filterPriority, filterCategory, search])

    const stats = useMemo(() => ({
        total: tasks.length,
        active: tasks.filter(t => t.status === "PENDING" || t.status === "IN_PROGRESS").length,
        done: tasks.filter(t => t.status === "DONE").length,
        urgent: tasks.filter(t => t.priority === "URGENT" && t.status !== "DONE" && t.status !== "DISMISSED").length,
    }), [tasks])

    const handleGenerate = useCallback(async () => {
        setGenerating(true)
        setGenerateMessage("")
        try {
            const res = await fetch("/api/tasks/generate", { method: "POST" })
            const data = await res.json()
            if (data.tasks?.length > 0) {
                setTasks(prev => [...data.tasks, ...prev])
                setGenerateMessage(`✦ ${data.tasks.length} tasks generated by AI`)
                setFilterStatus("ACTIVE")
            } else {
                setGenerateMessage(data.message || "No new tasks generated.")
            }
        } catch {
            setGenerateMessage("Failed to generate tasks. Please try again.")
        } finally {
            setGenerating(false)
            setTimeout(() => setGenerateMessage(""), 5000)
        }
    }, [])

    const handleStatusChange = useCallback(async (id: string, status: string) => {
        setTasks(prev => prev.map(t => t.id === id ? { ...t, status } : t))
        try {
            await fetch(`/api/tasks/${id}`, {
                method: "PATCH",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ status }),
            })
        } catch {
            // revert on error
            setTasks(prev => prev.map(t => t.id === id ? { ...t, status: t.status } : t))
        }
    }, [])

    const handleDelete = useCallback(async (id: string) => {
        setTasks(prev => prev.filter(t => t.id !== id))
        try {
            await fetch(`/api/tasks/${id}`, { method: "DELETE" })
        } catch {
            // silently fail
        }
    }, [])

    const handleAddTask = useCallback(async () => {
        if (!newTask.title.trim()) return
        setAddLoading(true)
        try {
            const res = await fetch("/api/tasks", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify(newTask),
            })
            const created = await res.json()
            setTasks(prev => [created, ...prev])
            setShowAddDialog(false)
            setNewTask({ title: "", description: "", priority: "MEDIUM", category: "" })
        } catch {
            // handle error
        } finally {
            setAddLoading(false)
        }
    }, [newTask])

    return (
        <div className="space-y-6">
            {/* Header */}
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                <div>
                    <h1 className="text-2xl font-bold text-slate-900 dark:text-white flex items-center gap-2">
                        <ClipboardList className="h-6 w-6 text-indigo-500" />
                        Task Manager
                    </h1>
                    <p className="text-sm text-slate-500 dark:text-slate-400 mt-0.5">
                        AI-powered tasks from your job applications
                    </p>
                </div>
                <div className="flex items-center gap-2">
                    <Button
                        variant="outline"
                        size="sm"
                        onClick={() => setShowAddDialog(true)}
                        className="rounded-xl"
                    >
                        <Plus className="h-4 w-4 mr-1.5" />
                        Add Task
                    </Button>
                    <Button
                        onClick={handleGenerate}
                        disabled={generating}
                        size="sm"
                        className="rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white shadow-lg shadow-indigo-500/20"
                    >
                        {generating
                            ? <RefreshCw className="h-4 w-4 mr-1.5 animate-spin" />
                            : <Sparkles className="h-4 w-4 mr-1.5" />
                        }
                        {generating ? "Generating…" : "Generate with AI"}
                    </Button>
                </div>
            </div>

            {/* AI message */}
            {generateMessage && (
                <div className="text-sm font-medium text-indigo-600 dark:text-indigo-400 bg-indigo-50 dark:bg-indigo-900/20 px-4 py-2.5 rounded-xl border border-indigo-200 dark:border-indigo-800">
                    {generateMessage}
                </div>
            )}

            {/* Stats */}
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                {[
                    { label: "Total", value: stats.total, color: "text-slate-700 dark:text-slate-200" },
                    { label: "Active", value: stats.active, color: "text-indigo-600 dark:text-indigo-400" },
                    { label: "Completed", value: stats.done, color: "text-green-600 dark:text-green-400" },
                    { label: "Urgent", value: stats.urgent, color: "text-red-600 dark:text-red-400" },
                ].map(s => (
                    <div key={s.label} className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 p-4 text-center">
                        <div className={cn("text-2xl font-bold", s.color)}>{s.value}</div>
                        <div className="text-xs text-slate-500 dark:text-slate-400 font-medium mt-0.5">{s.label}</div>
                    </div>
                ))}
            </div>

            {/* Filters */}
            <div className="flex flex-wrap gap-2 items-center">
                <Filter className="h-4 w-4 text-slate-400 shrink-0" />

                {/* Status tabs */}
                <div className="flex rounded-xl overflow-hidden border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900">
                    {[
                        { value: "ACTIVE", label: "Active" },
                        { value: "DONE", label: "Done" },
                        { value: "DISMISSED", label: "Dismissed" },
                        { value: "ALL", label: "All" },
                    ].map(opt => (
                        <button
                            key={opt.value}
                            onClick={() => setFilterStatus(opt.value)}
                            className={cn(
                                "px-3 py-1.5 text-xs font-semibold transition-colors",
                                filterStatus === opt.value
                                    ? "bg-indigo-600 text-white"
                                    : "text-slate-500 hover:text-slate-700 dark:text-slate-400 dark:hover:text-slate-200"
                            )}
                        >
                            {opt.label}
                        </button>
                    ))}
                </div>

                <Select value={filterPriority} onValueChange={setFilterPriority}>
                    <SelectTrigger className="h-8 w-32 rounded-xl text-xs">
                        <SelectValue placeholder="Priority" />
                    </SelectTrigger>
                    <SelectContent>
                        <SelectItem value="ALL">All Priorities</SelectItem>
                        <SelectItem value="URGENT">Urgent</SelectItem>
                        <SelectItem value="HIGH">High</SelectItem>
                        <SelectItem value="MEDIUM">Medium</SelectItem>
                        <SelectItem value="LOW">Low</SelectItem>
                    </SelectContent>
                </Select>

                <Select value={filterCategory} onValueChange={setFilterCategory}>
                    <SelectTrigger className="h-8 w-36 rounded-xl text-xs">
                        <SelectValue placeholder="Category" />
                    </SelectTrigger>
                    <SelectContent>
                        <SelectItem value="ALL">All Categories</SelectItem>
                        <SelectItem value="FOLLOW_UP">Follow Up</SelectItem>
                        <SelectItem value="INTERVIEW_PREP">Interview Prep</SelectItem>
                        <SelectItem value="APPLICATION">Application</SelectItem>
                        <SelectItem value="RESEARCH">Research</SelectItem>
                        <SelectItem value="NETWORKING">Networking</SelectItem>
                    </SelectContent>
                </Select>

                <Input
                    placeholder="Search tasks…"
                    value={search}
                    onChange={e => setSearch(e.target.value)}
                    className="h-8 w-48 rounded-xl text-xs"
                />
            </div>

            {/* Task list */}
            {filteredTasks.length === 0 ? (
                <div className="flex flex-col items-center justify-center py-20 text-center">
                    <CheckSquare className="h-12 w-12 text-slate-300 dark:text-slate-700 mb-3" />
                    <p className="text-slate-500 dark:text-slate-400 font-medium">
                        {tasks.length === 0
                            ? "No tasks yet. Click \"Generate with AI\" to get started!"
                            : "No tasks match your filters."}
                    </p>
                </div>
            ) : (
                <div className="space-y-2">
                    {filteredTasks.map(task => (
                        <TaskCard
                            key={task.id}
                            task={task}
                            onStatusChange={handleStatusChange}
                            onDelete={handleDelete}
                        />
                    ))}
                </div>
            )}

            {/* Add Task Dialog */}
            <Dialog open={showAddDialog} onOpenChange={setShowAddDialog}>
                <DialogContent className="sm:max-w-md rounded-2xl">
                    <DialogHeader>
                        <DialogTitle>Add Task</DialogTitle>
                    </DialogHeader>
                    <div className="space-y-3 py-2">
                        <Input
                            placeholder="Task title *"
                            value={newTask.title}
                            onChange={e => setNewTask(p => ({ ...p, title: e.target.value }))}
                            className="rounded-xl"
                        />
                        <Input
                            placeholder="Description (optional)"
                            value={newTask.description}
                            onChange={e => setNewTask(p => ({ ...p, description: e.target.value }))}
                            className="rounded-xl"
                        />
                        <div className="flex gap-2">
                            <Select value={newTask.priority} onValueChange={v => setNewTask(p => ({ ...p, priority: v }))}>
                                <SelectTrigger className="rounded-xl flex-1">
                                    <SelectValue />
                                </SelectTrigger>
                                <SelectContent>
                                    <SelectItem value="URGENT">Urgent</SelectItem>
                                    <SelectItem value="HIGH">High</SelectItem>
                                    <SelectItem value="MEDIUM">Medium</SelectItem>
                                    <SelectItem value="LOW">Low</SelectItem>
                                </SelectContent>
                            </Select>
                            <Select value={newTask.category} onValueChange={v => setNewTask(p => ({ ...p, category: v }))}>
                                <SelectTrigger className="rounded-xl flex-1">
                                    <SelectValue placeholder="Category" />
                                </SelectTrigger>
                                <SelectContent>
                                    <SelectItem value="FOLLOW_UP">Follow Up</SelectItem>
                                    <SelectItem value="INTERVIEW_PREP">Interview Prep</SelectItem>
                                    <SelectItem value="APPLICATION">Application</SelectItem>
                                    <SelectItem value="RESEARCH">Research</SelectItem>
                                    <SelectItem value="NETWORKING">Networking</SelectItem>
                                </SelectContent>
                            </Select>
                        </div>
                    </div>
                    <DialogFooter>
                        <Button variant="outline" onClick={() => setShowAddDialog(false)} className="rounded-xl">
                            Cancel
                        </Button>
                        <Button
                            onClick={handleAddTask}
                            disabled={!newTask.title.trim() || addLoading}
                            className="rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white"
                        >
                            {addLoading ? "Adding…" : "Add Task"}
                        </Button>
                    </DialogFooter>
                </DialogContent>
            </Dialog>
        </div>
    )
}
